name: Lint source code

on:
  push:
    branches: [master, main]
  pull_request:
    branches: ['*']

jobs:
  eslint:
    name: Eslint
    runs-on: ubuntu-latest
    container:
      image: node:14.17.0-alpine

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Lint source code with eslint
        run: npm run lint:eslint

  typechecking:
    name: Typechecking
    runs-on: ubuntu-latest
    container:
      image: node:14.17.0-alpine

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Run types checking
        run: npm run lint:ts

  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    container:
      image: node:14.17.0-alpine

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Lint source code with prettier
        continue-on-error: true
        run: npm run lint:prettier
