name: Lint source code

on:
  push:
    branches: [master, main]
  pull_request:
    branches: ['*']

jobs:
  linters:
    name: Linters
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install NVM
        run: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash

      - name: Install Node.js
        run: echo "lts/*" > .nvmrc

      - name: Install dependencies
        run: npm ci

      - name: Lint source code with prettier
        continue-on-error: true
        run: npm run lint:prettier

      - name: Lint source code with eslint
        run: npm run lint:eslint

      - name: Run types checking
        run: npm run lint:ts
