name: test

on:
  pull_request:
    branches: ['master']

jobs:
  name: Prettier
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - name: Install NVM
      run: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
    - name: Activate NVM
      run: export NVM_DIR="$HOME/.nvm" && . "$NVM_DIR/nvm.sh" --no-use
    - name: Install node.js
      env:
        NODE_VERSION: 14.17.0
      run: nvm install
    - name: Install dependencies
        run: npm ci
    - name: Lint source code with linters
        run: npm run link